{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.10409" %}
{% set llvm_version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/intel/intel-graphics-compiler/archive/igc-{{ version }}.tar.gz
    sha256: 233992605e1fd7e337e1457559ee6648a822f4b6e5c4894c5b11638d41f7e730

  - url: https://github.com/intel/vc-intrinsics/archive/4ce354da51f219bbdfa9c4cd5d8f640e92e38511.tar.gz
    sha256: e2904622dcf5f5e06d6c39b9e6a6d668c62ae5069515e8323dc9344ee9316174
    folder: vc-intrinsics

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - flex
    - bison
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
    - llvm-spirv {{ llvm_version }}
  run:
    - intel-opencl-clang {{ llvm_version }}
    - {{ pin_compatible("llvm-spirv", max_pin="x.x.x.x.x.x") }}

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.

extra:
  recipe-maintainers:
    - isuruf
