{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.17537.20" %}
{% set llvm_version = "14.0" %}
{% set vc_intrinsics_version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/intel/intel-graphics-compiler/archive/igc-{{ version }}.tar.gz
    folder: igc
    sha256: 44e77384ea69215d0311a08393019323f1c30217c05c972be945f2aed7fbde53
  # TODO: create separate package for the vc-intrinsics
  - url: https://github.com/intel/vc-intrinsics/archive/refs/tags/v{{ vc_intrinsics_version }}.tar.gz
    folder: vc-intrinsics
    sha256: 01a68a3c8299075ad2b094264bef5109d660f1d53faf614f4f95745ad05f4e3e

build:
  number: 0
  skip: true  # [not linux]
  script_env:
   - LLVM_VERSION={{ llvm_version }}
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - flex
    - bison
    - python *
    - mako
    - pyyaml
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
    - libllvmspirv {{ llvm_version }}
    - zlib
    - lld
    - spirv-tools
    - spirv-headers

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: igc/LICENSE.md
  license_family: MIT
  summary: The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
