{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.7041" %}
{% set llvm_version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/intel/intel-graphics-compiler/archive/igc-{{ version }}.tar.gz
    sha256: 299494ff885c8f0452c250867586be937a1aff9d46e6ff61a954bfc1e3a3c406

  - url: https://github.com/intel/vc-intrinsics/archive/d547de9478277e14896fa6418f6bb07ac07d7a1b.tar.gz
    sha256: 88944edb7abb28d3a8745727acc2fb934a5ea10059e25eeaf3c3169f534875fb
    folder: vc-intrinsics

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - flex
    - bison
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
    - llvm-spirv {{ llvm_version }}
  run:
    - intel-opencl-clang {{ llvm_version }}
    - {{ pin_compatible("llvm-spirv", max_pin="x.x.x.x.x.x") }}

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
