{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.6712" %}
{% set llvm_version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/intel-graphics-compiler/archive/igc-{{ version }}.tar.gz
  sha256: 1e5d63337ccbf8304c34b045b66e6e8411ce7d95b8f34c5abff17f6e60033eb0

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - flex
    - bison
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
  run:
    - intel-opencl-clang {{ llvm_version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.

extra:
  recipe-maintainers:
    - isuruf
